config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :comments, only: :create
  end
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択(任意)' },
    { id: 2, name: '10代' },
    { id: 3, name: '20代' },
    { id: 4, name: '30代' },
    { id: 5, name: '40代' },
    { id: 6, name: '50代' },
    { id: 7, name: '60代' },
    { id: 8, name: '70代' },
    { id: 9, name: '80代' },
    { id: 10, name: '90代以上' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択してください' },
    { id: 2, name: 'トップス' },
    { id: 3, name: 'ジャケット/アウター' },
    { id: 4, name: 'パンツ' },
    { id: 5, name: 'スカート' },
    { id: 6, name: 'オールインワン' },
    { id: 7, name: 'ワンピース' },
    { id: 8, name: 'スーツ' },
    { id: 9, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :comment, presence: true
end

app/models/figure.rb
class Figure < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択(任意)' },
    { id: 2, name: '細め' },
    { id: 3, name: '普通' },
    { id: 4, name: 'ふくよか' },
    { id: 5, name: '秘密' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/height.rb
class Height < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択(任意)' },
    { id: 2, name: '150cm以下' },
    { id: 3, name: '151cm〜160cm' },
    { id: 4, name: '161cm〜170cm' },
    { id: 5, name: '171cm〜180cm' },
    { id: 6, name: '181cm〜190cm' },
    { id: 7, name: '191cm以上' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  validates :category_id, numericality: { other_than: 1, message: 'を選択してください' }

  with_options presence: true do
    validates :image, :explanation
  end
end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択(任意)' },
    { id: 2, name: '男性' },
    { id: 3, name: '女性' },
    { id: 4, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/style.rb
class Style < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択(任意)' },
    { id: 2, name: 'カジュアル' },
    { id: 3, name: 'きれいめ' },
    { id: 4, name: 'シンプル' },
    { id: 5, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :height
  belongs_to :figure
  belongs_to :sex
  belongs_to :age
  belongs_to :style

  with_options presence: true do
    validates :name
    validates :user_name, uniqueness: { case_sensitive: true }, format: { with: /[a-z\d]/i }
  end

  VARID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,}+\z/i.freeze
  validates :password, format: { with: VARID_PASSWORD_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:name, :user_name, :height_id, :figure_id, :sex_id, :age_id, :style_id, :bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to item_path(params[:item_id])
    else
      @item = @comment.item
      @comments = @item.comments
      render 'items/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.order('RAND()').limit(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def edit
    redirect_to root_path unless current_user.id == @item.user.id
  end

  def update
    @item.update(item_params)
    if @item.save
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path unless current_user.id == @item.user_id
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:image, :category_id, :explanation).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>A KNOW | </title>

    <!-- Favicon  -->
    <link rel="icon" href="img/core-img/favicon.ico">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="/css/core-style.css">
    <link rel="stylesheet" href="/style.css">

</head>

<body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="#" method="get">
                            <input type="search" name="search" id="search" placeholder="Type your keyword...">
                            <button type="submit"><img src="/img/core-img/search.png" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="index.html"><img src="/img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <%= link_to image_tag("/img/core-img/logo.png", class:"aknow-icon"), "/" %>
            </div>
            <% if user_signed_in? %>
            <div class="profile">
                <div class="card card-testimonial bg-light">
                    <div class="card-body d-flex flex-row align-items-center pb-3">
                        <img src="/img/core-img/default_icon.png" class="img-avatar rounded-circle" alt="Avatar image" width="50" height="50">
                        <div class="d-flex flex-column">
                            <span class="person small ml-2"><strong><%= link_to current_user.name, "#", class: "user-name" %></strong></span>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
            <nav class="amado-nav">
                <ul>
                    <li class="active"><%= link_to 'TOP', root_path, class: "top-page" %></li>
                    <!--<li><a href="shop.html">カテゴリー</a></li>-->
                    <% if user_signed_in? %>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
                    <% else %>
                    <li><%= link_to '新規会員登録', new_user_registration_path, class: "sign-up" %></li>
                    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
                    <% end %>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">
                <%=link_to 'A KNOW', new_item_path, class:"btn amado-btn mb-15" %>
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a href="#" class="fav-nav"><img src="/img/core-img/favorites.png" alt=""> Bookmark</a>
                <a href="#" class="search-nav"><img src="/img/core-img/search.png" alt=""> Search</a>
            </div>
        </header>
        <!-- Header Area End -->

        <div class="cart-table-area section-padding-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        <div class="checkout_details_area mt-50 clearfix">

                            <div class="cart-title text-center">
                                <h2>投稿編集</h2>
                            </div>

                            <%= form_with model: @item, local: true do |f| %>
                            <%= render 'shared/error', model: f.object %>
                                <div class="row">
                                    <div class="form-group col-md-8 offset-md-2 mt-3 mb-3">
                                        <label for="exampleFormControlFile1">　画像</label>
                                        <span class="indispensable badge badge-danger">必須</span>
                                        <%= f.file_field :image, class:"form-control-file", id:"item-image" %>
                                    </div>
                                    <div class="col-md-8 offset-md-2 mt-3 mb-3">
                                    <label class="form-label">　カテゴリー</label>
                                    <span class="indispensable badge badge-danger">必須</span>
                                        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box w-100", id:"item-category"}) %>
                                    </div>
                                    <div class="col-md-8 offset-md-2 mt-3 mb-3">
                                    <label class="form-label">　アイテム説明</label>
                                    <span class="indispensable badge badge-danger">必須</span>
                                        <%= f.text_area :explanation, class:"form-control mb-3", id:"explanation", placeholder:"アイテム説明を入力してください" ,rows:"5" ,maxlength:"1000" %>
                                    </div>
                                    <div class="d-flex align-items-center justify-content-center login-btn mb-50">
                                        <%= f.submit "編集する" ,class:"btn amado-btn mr-50" %>
                                        <%= link_to "削除", item_path(@item.id), method: :delete, class:"btn amado-btn active" %>
                                    </div>
                                    <div class="d-flex align-items-center justify-content-center login-btn mb-50">
                                        <%=link_to 'キャンセル', item_path(@item.id), class:"btn amado-btn w-50" %>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Main Content Wrapper End ##### -->

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <%= link_to image_tag("/img/core-img/logo_bk.png", class:"aknow-icon2"), "/" %>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> & Re-distributed by <a href="https://themewagon.com/" target="_blank">Themewagon</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <%= link_to 'TOP', root_path, class: "nav-link" %>
                                        </li>
                                        <!--<li class="nav-item">
                                            <a class="nav-link" href="shop.html">カテゴリー</a>
                                        </li>-->
                                        <% if user_signed_in? %>                                    
                                        <li class="nav-item">
                                            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %>
                                        </li>
                                        <% else %>
                                        <li class="nav-item">
                                            <%= link_to '新規会員登録', new_user_registration_path, class: "nav-link" %>
                                        </li>
                                        <li class="nav-item">
                                            <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
                                        </li>
                                        <% end %>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="/js/plugins.js"></script>
    <!-- Active js -->
    <script src="/js/active.js"></script>

</body>

</html>

app/views/items/show.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>A KNOW | </title>

    <!-- Favicon  -->
    <link rel="icon" href="img/core-img/favicon.ico">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="/css/core-style.css">
    <link rel="stylesheet" href="/style.css">

</head>

<body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="#" method="get">
                            <input type="search" name="search" id="search" placeholder="Type your keyword...">
                            <button type="submit"><img src="/img/core-img/search.png" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="index.html"><img src="/img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <%= link_to image_tag("/img/core-img/logo.png", class:"aknow-icon"), "/" %>
            </div>
            <% if user_signed_in? %>
            <div class="profile">
                <div class="card card-testimonial bg-light">
                    <div class="card-body d-flex flex-row align-items-center pb-3">
                        <img src="/img/core-img/default_icon.png" class="img-avatar rounded-circle" alt="Avatar image" width="50" height="50">
                        <div class="d-flex flex-column">
                            <span class="person small ml-2"><strong><%= link_to current_user.name, "#", class: "user-name" %></strong></span>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li class="active"><%= link_to 'TOP', root_path, class: "top-page" %></li>
                    <!--<li><a href="shop.html">カテゴリー</a></li>-->
                    <% if user_signed_in? %>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
                    <% else %>
                    <li><%= link_to '新規会員登録', new_user_registration_path, class: "sign-up" %></li>
                    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
                    <% end %>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">
                <%=link_to 'A KNOW', new_item_path, class:"btn amado-btn mb-15" %>
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a href="#" class="fav-nav"><img src="/img/core-img/favorites.png" alt=""> Bookmark</a>
                <a href="#" class="search-nav"><img src="/img/core-img/search.png" alt=""> Search</a>
            </div>
        </header>
        <!-- Header Area End -->

        <!-- Product Details Area Start -->
        <div class="single-product-area section-padding-100 clearfix">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb mt-50">
                                <li class="breadcrumb-item"><%= link_to 'TOP', root_path, class: "top-page" %></li>
                                <li class="breadcrumb-item"><%= @item.category.name %></li>
                            </ol>
                        </nav>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-7">
                        <div class="single_product_thumb">
                            <%= image_tag @item.image.variant(resize: '500<'), class: "d-block w-100" %>
                        </div>
                    </div>
                    <div class="col-12 col-lg-5">
                        <div class="single_product_desc">
                            <!-- Product Meta Data -->
                            <div class="product-meta-data">
                                <div class="line"></div>
                                <p class="product-price"><%= l @item.created_at %></p>
                                <a href="#">
                                    <h6><%= @item.user.name %></h6>
                                </a>
                            </div>
                            <!-- Explanation -->
                            <div class="short_overview my-5 mb-100">
                                <p><%= @item.explanation %></p>
                            </div>
                            <div class="cart clearfix cart-btn d-flex w-100">
                                <% if user_signed_in? %>
                                    <% if current_user.id == @item.user_id %>
                                        <%= link_to "編集／削除", edit_item_path(@item.id), method: :get, class:"btn amado-btn" %>
                                    <% else %>
                                        <div class="row">
                                            <%= form_with model: [@item, @comment],local: true do |f| %>
                                            <%= f.text_area :comment, class:"form-control mb-3 w-100", id:"comment", placeholder:"ANSWERを入力してください" ,rows:"3" ,maxlength:"500" %>
                                            <%= f.submit "ANSWER", class:"btn amado-btn" %>
                                            <% end %>
                                        </div>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
               <div id="comments">
                    <div class="mb-4">
                        <h3>　ANSWER</h3>
                    </div>
                    <% @item.comments.each do |comment| %>
                    <div class="comment mb-4">
                        <p class="user-info"><h6>　<%= comment.user.name %></h6></p>
                        <p>　<%= comment.comment%></p>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
        <!-- Product Details Area End -->
    </div>
    <!-- ##### Main Content Wrapper End ##### -->

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <%= link_to image_tag("/img/core-img/logo_bk.png", class:"aknow-icon2"), "/" %>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> & Re-distributed by <a href="https://themewagon.com/" target="_blank">Themewagon</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <%= link_to 'TOP', root_path, class: "nav-link" %>
                                        </li>
                                        <!--<li class="nav-item">
                                            <a class="nav-link" href="shop.html">カテゴリー</a>
                                        </li>-->
                                        <% if user_signed_in? %>                                    
                                        <li class="nav-item">
                                            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %>
                                        </li>
                                        <% else %>
                                        <li class="nav-item">
                                            <%= link_to '新規会員登録', new_user_registration_path, class: "nav-link" %>
                                        </li>
                                        <li class="nav-item">
                                            <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
                                        </li>
                                        <% end %>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="/js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="/js/plugins.js"></script>
    <!-- Active js -->
    <script src="/js/active.js"></script>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aknow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_side-bar.html.erb
<!-- Mobile Nav (max width 767px)-->
<div class="mobile-nav">
    <!-- Navbar Brand -->
    <div class="amado-navbar-brand">
        <a href="index.html"><img src="img/core-img/logo.png" alt=""></a>
    </div>
    <!-- Navbar Toggler -->
    <div class="amado-navbar-toggler">
        <span></span><span></span><span></span>
    </div>
</div>

<!-- Header Area Start -->
<header class="header-area clearfix">
    <!-- Close Icon -->
    <div class="nav-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <!-- Logo -->
    <div class="logo">
        <%= link_to image_tag("/img/core-img/logo.png", class:"aknow-icon"), "/" %>
    </div>
    <% if user_signed_in? %>
    <div class="profile">
        <div class="card card-testimonial bg-light">
            <div class="card-body d-flex flex-row align-items-center pb-3">
                <img src="img/core-img/default_icon.png" class="img-avatar rounded-circle" alt="Avatar image" width="50" height="50">
                <div class="d-flex flex-column">
                    <span class="person small ml-2"><strong><%= link_to current_user.name, "#", class: "user-name" %></strong></span>
                </div>
            </div>
        </div>
     </div>
     <% end %>
    <!-- Amado Nav -->
    <nav class="amado-nav">
        <ul>
            <li class="active"><%= link_to 'TOP', root_path, class: "top-page" %></li>
            <!--<li><a href="shop.html">カテゴリー</a></li>-->
            <% if user_signed_in? %>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
            <% else %>
            <li><%= link_to '新規会員登録', new_user_registration_path, class: "sign-up" %></li>
            <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
            <% end %>
        </ul>
    </nav>
    <!-- Button Group -->
    <div class="amado-btn-group mt-30 mb-100">
        <%=link_to 'A KNOW', new_item_path, class:"btn amado-btn mb-15" %>
    </div>
    <!-- Cart Menu -->
    <div class="cart-fav-search mb-100">
        <a href="#" class="fav-nav"><img src="img/core-img/favorites.png" alt=""> Bookmark</a>
        <a href="#" class="search-nav"><img src="img/core-img/search.png" alt=""> Search</a>
    </div>
</header>
<!-- Header Area End -->